name: Atualização do Servidor Minecraft

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Instalar o Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    - name: Verificar saídas do Docker
      run: docker ps -a

    - name: Parar o contêiner existente
      run: docker stop ifce-minecraft-server || true

    - name: Remover o contêiner existente
      run: docker rm ifce-minecraft-server || true

    - name: Construir a imagem do servidor Minecraft
      run: docker build -t ifce-minecraft-server .

    - name: Executar o contêiner do servidor Minecraft
      run: docker run -d -p 25565:25565 --name ifce-minecraft-server ifce-minecraft-server
