name: Atualização do Servidor Minecraft

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v2
      
    - name: Instalar o Docker
      run: |
        sudo apt-get update
        sudo apt-get remove -y containerd.io
        sudo apt-get clean
        sudo apt-get -f install -y
        sudo apt-get install -y docker.io

    - name: Verificar saídas do Docker
      run: docker ps -a

    - name: Parar o contêiner existente
      run: docker stop ifce-minecraft-server || true

    - name: Remover o contêiner existente
      run: docker rm ifce-minecraft-server || true

    - name: Construir a imagem do servidor Minecraft
      run: docker build -t ifce-minecraft-server .

    - name: Publicar a imagem no Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag da imagem
      run: docker tag ifce-minecraft-server ${{ secrets.DOCKER_USERNAME }}/ifce-minecraft-server:latest

    - name: Enviar imagem para o Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/ifce-minecraft-server:latest

    - name: Atualizar contêiner
      run: docker stop ifce-minecraft-server && docker rm ifce-minecraft-server && docker run -d --restart=always -p 25565:25565 -p 24454:24454/udp --name ifce-minecraft-server ifce-minecraft-server
